### ISSUE TITLE
Pin dependency version

### ISSUE THREAD

**Issue by mrleblanc101** [intlify/cli#64]
### Reporting a bug?

`@intlify/cli` has some unpinned dependency.
So when I run `yarn upgrade`, my project break because one of these 3 package does not support node 14.
```
"@intlify/bundle-utils" next
"@intlify/core" beta
"@intlify/shared" beta
```

### Expected behavior

The dependency should be pinned as to not cause this error:
> @intlify/shared@9.4.1: The engine "node" is incompatible with this module. Expected version ">= 16". Got "14.21.3"

### Reproduction

.

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) x64 Apple M1 Pro
    Memory: 111.79 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/cli/blob/main/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://github.com/intlify/cli/blob/main/README.md)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/cli/discussions)

**Comment by mrleblanc101** [comment]
I'm not sure if there is a way to run `yarn upgrade` while excluding these packages.

**Comment by mrleblanc101** [comment]
That was quick, I'll test tomorrow. 
Thanks

**Comment by mrleblanc101** [comment]
The pin to `^9.4.1` is incompatible with node 14, sadly I can't migrate so I guess i'll stay with the current version of my dependencies.

**Comment by kazupon** [comment]
Unfortunately, Node v14 and v16 were already EOL. 😞 
If you need to use `@intlify/cli`, I think you can use the override features of the package manager.

**Comment by mrleblanc101** [comment]
I use vue-i18n-locale-message which seams to use @intlify/cli
